### PR TITLE
add graphical interface to hangman

### PR DESCRIPTION
**Pull request by 92username**
This pull request includes major updates to the Hangman game project, focusing on enhancing the user interface, improving the game logic, and updating the documentation. The most important changes include the addition of a graphical user interface using `tkinter`, the implementation of a new game class, and extensive updates to the `README.md` file.

### User Interface Enhancements:
* [`main.py`](diffhunk://#diff-b10564ab7d2c520cdd0243874879fb0a782862c3c902ab535faabe57d5a505e1L1-R167): Introduced a new `HangmanGame` class that uses `tkinter` for the graphical interface, including methods for creating widgets, checking guesses, updating the game state, and drawing the hangman.
* [`menu.py`](diffhunk://#diff-9633182b5bc44116a1dad564c96a21924ed7c84ac01a1ef272575d164a3a4703L1-R95): Replaced the text-based menu with a graphical menu using `tkinter`, adding buttons to select word categories and start the game. The menu now logs initialization and widget creation times for debugging purposes.

### Game Logic Improvements:
* [`main.py`](diffhunk://#diff-b10564ab7d2c520cdd0243874879fb0a782862c3c902ab535faabe57d5a505e1L1-R167): Refactored the game logic to be encapsulated within the `HangmanGame` class, including methods for handling game restarts and checking win conditions.

### Documentation Updates:
* [`README.md`](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L1-R69): Expanded the documentation to include detailed instructions on how to run the game, a list of features, and images of the game interface. The README now provides a comprehensive guide for new users and contributors.

### CODE REVIEW

**Comment by steven-dev8** [comment]
> This pull request includes major updates to the Hangman game project, focusing on enhancing the user interface, improving the game logic, and updating the documentation. The most important changes include the addition of a graphical user interface using `tkinter`, the implementation of a new game class, and extensive updates to the `README.md` file.
> 
> ### User Interface Enhancements:
> * [`main.py`](https://github.com/steven-dev8/hangman/pull/1/files#diff-b10564ab7d2c520cdd0243874879fb0a782862c3c902ab535faabe57d5a505e1L1-R167): Introduced a new `HangmanGame` class that uses `tkinter` for the graphical interface, including methods for creating widgets, checking guesses, updating the game state, and drawing the hangman.
> * [`menu.py`](https://github.com/steven-dev8/hangman/pull/1/files#diff-9633182b5bc44116a1dad564c96a21924ed7c84ac01a1ef272575d164a3a4703L1-R95): Replaced the text-based menu with a graphical menu using `tkinter`, adding buttons to select word categories and start the game. The menu now logs initialization and widget creation times for debugging purposes.
> 
> ### Game Logic Improvements:
> * [`main.py`](https://github.com/steven-dev8/hangman/pull/1/files#diff-b10564ab7d2c520cdd0243874879fb0a782862c3c902ab535faabe57d5a505e1L1-R167): Refactored the game logic to be encapsulated within the `HangmanGame` class, including methods for handling game restarts and checking win conditions.
> 
> ### Documentation Updates:
> * [`README.md`](https://github.com/steven-dev8/hangman/pull/1/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L1-R69): Expanded the documentation to include detailed instructions on how to run the game, a list of features, and images of the game interface. The README now provides a comprehensive guide for new users and contributors.

**Comment by steven-dev8** [comment]
> Este pull request inclui atualizações importantes para o projeto do jogo Hangman, com foco em aprimorar a interface do usuário, melhorar a lógica do jogo e atualizar a documentação. As mudanças mais importantes incluem a adição de uma interface gráfica do usuário usando `tkinter`, a implementação de uma nova classe de jogo e atualizações extensivas para o `README.md`arquivo.
> 
> ### Melhorias na interface do usuário:
> * [`main.py`](https://github.com/steven-dev8/hangman/pull/1/files#diff-b10564ab7d2c520cdd0243874879fb0a782862c3c902ab535faabe57d5a505e1L1-R167): Foi introduzida uma nova `HangmanGame`classe que usa `tkinter`a interface gráfica, incluindo métodos para criar widgets, verificar palpites, atualizar o estado do jogo e desenhar o jogo da forca.
> * [`menu.py`](https://github.com/steven-dev8/hangman/pull/1/files#diff-9633182b5bc44116a1dad564c96a21924ed7c84ac01a1ef272575d164a3a4703L1-R95): Substituiu o menu baseado em texto por um menu gráfico usando `tkinter`, adicionando botões para selecionar categorias de palavras e iniciar o jogo. O menu agora registra os tempos de inicialização e criação de widgets para fins de depuração.
> 
> ### Melhorias na lógica do jogo:
> * [`main.py`](https://github.com/steven-dev8/hangman/pull/1/files#diff-b10564ab7d2c520cdd0243874879fb0a782862c3c902ab535faabe57d5a505e1L1-R167): Refatorou a lógica do jogo para ser encapsulada dentro da `HangmanGame`classe, incluindo métodos para lidar com reinicializações do jogo e verificar condições de vitória.
> 
> ### Atualizações da documentação:
> * [`README.md`](https://github.com/steven-dev8/hangman/pull/1/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L1-R69): A documentação foi expandida para incluir instruções detalhadas sobre como executar o jogo, uma lista de recursos e imagens da interface do jogo. O README agora fornece um guia abrangente para novos usuários e colaboradores.

**Comment by steven-dev8** [comment]
Thanks, 92username. Actually, I am learning POO, and I will implement POO in my future projects.

**Comment by 92username** [comment]
tmj

**Pull request merged**
